
-- Bulk insert treatments
-- Uses ON CONFLICT to avoid errors if run multiple times

INSERT INTO treatments (title, slug, is_active)
VALUES
('Adenoidectomy', 'adenoidectomy', true),
('Anal Fissure', 'anal-fissure', true),
('Anal Fistula', 'anal-fistula', true),
('Antepartum and Intrapartum Monitoring', 'antepartum-and-intrapartum-monitoring', true),
('Appendicitis', 'appendicitis', true),
('Arthroscopy Surgery', 'arthroscopy-surgery', true),
('Back Pain', 'back-pain', true),
('Balanitis', 'balanitis', true),
('Balanoposthitis', 'balanoposthitis', true),
('Bariatric Surgery', 'bariatric-surgery', true),
('Cancer Care', 'cancer-care', true),
('Chronic Disease Management', 'chronic-disease-management', true),
('Circumcision', 'circumcision', true),
('Corn Removal', 'corn-removal', true),
('Diabetic Foot Ulcers', 'diabetic-foot-ulcers', true),
('Diagnostic Procedure', 'diagnostic-procedure', true),
('DVT', 'dvt', true),
('Ear Surgery', 'ear-surgery', true),
('Elbow Pain', 'elbow-pain', true),
('Enlarged Prostate', 'enlarged-prostate', true),
('ESWL', 'eswl', true),
('Fertility Services', 'fertility-services', true),
('Fissure Surgery', 'fissure-surgery', true),
('Foot or Ankle Pain', 'foot-or-ankle-pain', true),
('Foreskin Infection', 'foreskin-infection', true),
('Frenuloplasty Surgery', 'frenuloplasty-surgery', true),
('Gallstone', 'gallstone', true),
('Gastrointestinal Issues', 'gastrointestinal-issues', true),
('Headache or Migraine', 'headache-or-migraine', true),
('Hernia', 'hernia', true),
('High Risk Pregnancy Management', 'high-risk-pregnancy-management', true),
('Hip Pain', 'hip-pain', true),
('Hip Replacement Surgery', 'hip-replacement-surgery', true),
('Hoodecomy', 'hoodecomy', true),
('Hydrocele', 'hydrocele', true),
('Hymenoplasty', 'hymenoplasty', true),
('Incisional Hernia', 'incisional-hernia', true),
('Inguinal Hernia', 'inguinal-hernia', true),
('Intragastric Balloon', 'intragastric-balloon', true),
('Kidney Stones', 'kidney-stones', true),
('Knee Arthroscopy', 'knee-arthroscopy', true),
('Knee Pain', 'knee-pain', true),
('Labiaplasty', 'labiaplasty', true),
('Labor & Delivery', 'labor-delivery', true),
('Management of Infections', 'management-of-infections', true),
('Mastoidectomy', 'mastoidectomy', true),
('Meniscus Tear', 'meniscus-tear', true),
('Mental Health', 'mental-health', true),
('Metabolic and Endocrine Disorders', 'metabolic-and-endocrine-disorders', true),
('Minimally Invasive Surgery', 'minimally-invasive-surgery', true),
('Monoplasty', 'monoplasty', true),
('Myringotomy', 'myringotomy', true),
('Nasal Polyps', 'nasal-polyps', true),
('Neck Pain', 'neck-pain', true),
('Paraphimosis', 'paraphimosis', true),
('PCNL', 'pcnl', true),
('Pelvic Floor Disorders', 'pelvic-floor-disorders', true),
('Perianal Abscess', 'perianal-abscess', true),
('Phimosis', 'phimosis', true),
('Piles', 'piles', true),
('Pilonidal Sinus', 'pilonidal-sinus', true),
('Postpartum Care', 'postpartum-care', true),
('Prenatal Care', 'prenatal-care', true),
('Prostatectomy', 'prostatectomy', true),
('Rectal Prolapse', 'rectal-prolapse', true),
('Respiratory', 'respiratory', true),
('RIRS', 'rirs', true),
('Rotator Cuff Repair', 'rotator-cuff-repair', true),
('Septoplasty', 'septoplasty', true),
('Shoulder Arthroscopy', 'shoulder-arthroscopy', true),
('Shoulder Dislocation', 'shoulder-dislocation', true),
('Shoulder Pain', 'shoulder-pain', true),
('Shoulder Replacement', 'shoulder-replacement', true),
('Sinus', 'sinus', true),
('Spine Surgery', 'spine-surgery', true),
('Sports Pain', 'sports-pain', true),
('Stapedectomy', 'stapedectomy', true),
('Stapler Circumcision', 'stapler-circumcision', true),
('Surgical Interventions', 'surgical-interventions', true),
('Swollen Penis', 'swollen-penis', true),
('Throat Surgery', 'throat-surgery', true),
('Thyroidectomy', 'thyroidectomy', true),
('Tonsillectomy', 'tonsillectomy', true),
('Total Knee Replacement', 'total-knee-replacement', true),
('Turbinate Reduction', 'turbinate-reduction', true),
('Tympanoplasty', 'tympanoplasty', true),
('URSL', 'ursl', true),
('Vaginoplasty', 'vaginoplasty', true),
('Varicocele', 'varicocele', true),
('Varicose Veins', 'varicose-veins', true),
('Vocal Cord Polyps', 'vocal-cord-polyps', true),
('Rhinoplasty', 'rhinoplasty', true),
('Umbilical Hernia', 'umbilical-hernia', true),
('Uterine Fibroids', 'uterine-fibroids', true),
('Vestoplasty', 'vestoplasty', true)
ON CONFLICT (slug) DO NOTHING;
